version: '3.9'

services:
  server-db:
    image: 'postgres:11'
    environment:
      ENVIRONMENT: 'docker'
    env_file:
      - ./configs/.env-docker
    expose:
      - 5432
    ports:
      - '5434:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:6.0-buster'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    expose:
      - 6379
    ports:
      - '6380:6379'

  server:
    build: .
    depends_on:
      - server-db
      - redis
    command:
      bash -c 'while !</dev/tcp/server-db/5432; do sleep 20; done; flask db upgrade
      && gunicorn -b 0.0.0.0:8000 --access-logfile - --reload "wsgi:flask_app"'
    environment:
      PYTHONUNBUFFERED: 'true'
      ENVIRONMENT: 'docker'
    volumes:
      - '.:/python-sample'
    ports:
      - '8000:8000'
    restart: always
